FROM mcr.microsoft.com/dotnet/aspnet:8.0

ENV ASPNETCORE_HTTP_PORTS=8080

WORKDIR /app

COPY --chown=app:app /docker/app .

LABEL maintainer="Miłosz Gilga <miloszgilga@gmail.com>"

EXPOSE 8080

USER app

ENTRYPOINT ["dotnet", "ScheduleManagement.dll"]
