// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_net_po_schedule_management_server.DbConfig;

namespace asp_net_po_schedule_management_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("asp_net_po_schedule_management_server.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppLogin")
                        .HasColumnType("longtext")
                        .HasColumnName("app-login");

                    b.Property<string>("AppPassword")
                        .HasColumnType("longtext")
                        .HasColumnName("app-password");

                    b.Property<string>("PersonIdentifier")
                        .HasColumnType("longtext")
                        .HasColumnName("person-identifier");

                    b.Property<string>("PersonShortcut")
                        .HasColumnType("longtext")
                        .HasColumnName("person-shortcut");

                    b.HasKey("Id");

                    b.ToTable("persons-table");
                });
#pragma warning restore 612, 618
        }
    }
}
